---
- name: 安装 Zsh
  become: true
  package:
    name: zsh
    state: present

- name: 检查 Oh My Zsh 是否存在
  stat:
    path: "{{ ansible_facts.env.HOME }}/.oh-my-zsh"
  register: omz_dir

- name: 安装 Oh My Zsh
  shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ ansible_facts.env.HOME }}/.oh-my-zsh"
  when: not omz_dir.stat.exists

- name: 安装 Oh My Zsh 插件
  git:
    repo: "{{ item.repo }}"
    dest: "{{ zsh_custom }}/plugins/{{ item.name }}"
  loop: "{{ zsh_plugins }}"

- name: 安装 Powerlevel10k 主题
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: "{{ zsh_custom }}/themes/powerlevel10k"

- name: 获取 Zsh 路径
  command: which zsh
  register: zsh_path
  changed_when: false

- name: 设置 Zsh 为默认 Shell
  become: true
  user:
    name: "{{ ansible_facts.user_id }}"
    shell: "{{ zsh_path.stdout }}"